apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dep
  labels:
    app: micro-gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-gatewayserver
  template:
    metadata: 
      labels:
        app: micro-gatewayserver
    spec: 
      containers:
        - name: micro-gatewayserver
          image: dfrestrepo1998/microservicio_gatewayserver:1.0.0
          ports:
          - containerPort: 8072
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef: 
                name: micropro-configmap
                key: profiles-active
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef: 
                name: micropro-configmap
                key: config-import   
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef: 
                name: micropro-configmap
                key: eureka-serviceurl  
---
apiVersion: v1
kind: Service
metadata:
  name: micro-gatewayserver-service
spec:
  selector:
    app: micro-gatewayserver
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
  type: LoadBalancer